### ISSUE TITLE
Create Django model prototypes

### ISSUE THREAD

**Issue by lamby** [openhealthcare/python-fp17#10]

**Comment by lamby** [comment]
See also https://github.com/odonto/odonto/blob/master/odonto/models.py#L78

**Comment by fredkingham** [comment]
So...
There is already a prototype application that I had not realised.

The prototype application is an opal application and we _are_ aiming to end up with an opal application. Although they way this interacts with upstream could well be raw django.

(presumably admin forms, which in opal is just vanilla django admin, maybe celery tasks?).

The models as designed in the above application are designed around  how the paper form was written.

This means that there is a good chance that these are not necessarily the models that we would want to use. 

I feel like some explanation on how the pathway below extrapolates metadata from the models and how the patient/episode model in opal works may actually be in order

https://github.com/odonto/odonto/blob/master/odonto/pathways.py

Sorry about the confusion!
