### ISSUE TITLE
Trouble building Sphinx automodule

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/python-fp17#5]
When invoked with e.g. `make html` the built Sphinx documentation only seems to contain a copyright notice.

...It's been ages since I tried to wrangle Sphinx / rst in anger but from memory it needs you to mess about with python paths for automodule to work?

Of course I could be using the wrong incantation.

**Comment by lamby** [comment]
> Of course I could be using the wrong incantation.

Nope; I added this already before :)  https://github.com/openhealthcare/python-fp17/blob/master/docs/conf.py#L23-L25
