### ISSUE TITLE
I _think_ this should yield rather than return, but fairly sure it shouldn't be "both"

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/python-fp17#7]
`fp17.bcds1.Treatment` looks like this has crept in:

```
    def validate(self, document):
        return
        yield
```
https://github.com/openhealthcare/python-fp17/blob/master/fp17/bcds1.py#L131

**Comment by lamby** [comment]
Muhahaha no, it **should** be both! Will add a comment …

**Comment by davidmiller** [comment]
It's shorthand for `raise StopIteration` (ish)

TIL.
